name: 'Check Lingua Franca files'
description: 'Ensure that all Lingua Franca files compile'
author: 'Marten Lohstroh'
inputs:
  compiler_ref:
    required: false
    description: 'Ref of the compiler to check against'
    default: 'master'
  checkout_dir:
    required: false
    description: 'The directory in which to check out the lingua-franca repo'
    default: 'lingua-franca'
  delete_if_exists:
    required: false
    description: 'Delete the checkout directory if it exists prior to cloning'
    default: false
  skip_clone:
    required: false
    description: 'Use existing clone of lingua-franca'
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
