name: 'Check Lingua Franca files'
description: 'Ensure that all Lingua Franca files compile'
author: 'Marten Lohstroh'
inputs:
  compiler-ref:
    required: false
    description: 'Ref to the compiler to check against'
    default: 'master'
  checkout-dir:
    required: false
    description: 'The directory in which to check out the lingua-franca repo'
    default: 'lingua-franca'
runs:
  using: 'node16'
  main: 'dist/index.js'
